apiVersion: apps/v1
kind: Deployment
metadata:
    name: cvapp
spec:
   replicas: 2
   selector:
     matchLabels:
        templateName: cvdapp
        stage: production
   template:
     metadata:
        labels:
          templateName: cvdapp
          stage: production
     spec:
       containers:
        - image: lipun1/prasad:latest
          name: lipun1
          ports:
           - containerPort: 8081
             name: http
             protocol: TCP
