apiVersion: v1
kind: ResourceQuota
metadata: 
   name: limitsmemorypod
   namespace: quota-example
spec:
  containers:
   - name: nginxapp
     image: nginx:latest
     ports:
      - containerPort: 8081
        protocol: TCP
        name: http
     resources:
       requests:
         memory: 1Gi
       limits:
         memory: 1Gi
