apiVersion: batch/v1
kind: Job
metadata:
    name: lk
spec:
   template: 
       spec:
         containers:
             - name: pl
               image: perl
               command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
         restartPolicy: Never
   backoffLimit: 2
